# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14)),
                ('currency', models.DecimalField(decimal_places=0, max_digits=3)),
                ('locked_out', models.BooleanField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('balance', models.DecimalField(decimal_places=0, max_digits=16)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('dt_bank', models.DateTimeField()),
                ('docnum', models.CharField(max_length=10)),
                ('code_bank_a', models.DecimalField(decimal_places=0, max_digits=9)),
                ('account_a', models.DecimalField(decimal_places=0, max_digits=14)),
                ('client_a', models.CharField(max_length=38)),
                ('ident_a', models.CharField(max_length=10)),
                ('code_bank_b', models.DecimalField(decimal_places=0, max_digits=9)),
                ('account_b', models.DecimalField(decimal_places=0, max_digits=14)),
                ('client_b', models.CharField(max_length=38)),
                ('ident_b', models.CharField(max_length=10)),
                ('debit_credit', models.BooleanField()),
                ('kind', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, null=True)),
                ('purpose', models.TextField()),
                ('amount_nv', models.DecimalField(decimal_places=0, max_digits=16, null=True)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Users_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=14)),
                ('access_mode', models.BooleanField()),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
            options={
                'db_table': 'users_accounts',
            },
        ),
    ]
