# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_users_accounts_id_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=80)),
                ('locked_out', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='users_accounts',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Users'),
        ),
    ]
