# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20161006_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='dt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documents',
            name='dt_bank',
            field=models.TextField(),
        ),
    ]
